kernel: selinux/rules: Pin task to current CPU to avoid cross-CPU rwlock release
Injecting SELinux policy rules on the fly requires us to modify policy
structures that are protected by a kernel read/write lock. But this procedure of
applying the rules comes with memory allocation, copying the rules and deliver
to userspace and they need to *sleep*. And here we go with the clash of kernel
locking rules where sleeping while holding an rwlock (which is atomic) is
illegal.

To workaround this, the original implementation introduced a nasty hack:
1. Acquire write lock.
2. Immediately force-enable preemption using preempt_enable().
3. Call lockdep_off() to make lockdep go blind (We'll come to this later).

This allows the code to perform its sleeping memory allocations without
immediately triggering a "sleeping in invalid (atomic) context" call trace with
lockdep on (naturally).

But there's a catch. Because preemption is enabled while the lock is held, the
kernel's scheduler is free to migrate the sleeping task to a completely
different CPU in the meantime according to the judgement of its load balancer.

When the task wakes up and finishes its work, it tries to release the write lock
from its new CPU. That's why lockdep_off/on was put there to go blind
intentionally and overlook it. With the lockdep_off/on() removed and lockdep
being enabled, we are greeted with the following splat:

[    5.251305] BUG: rwlock wrong CPU on CPU#1, init/391, 000000000d270d12
[    5.251318] CPU: 1 PID: 391 Comm: init Tainted: G        W         5.4.295-Scarlet-v4.1-@8c8206ad #1
[    5.251323] Hardware name: redwood based Qualcomm Technologies, Inc. SM7325 (DT)
[    5.251329] Call trace:
[    5.251341] dump_backtrace+0x0/0x1a0
[    5.251347] show_stack+0x14/0x20
[    5.251356] __dump_stack+0x20/0x30
[    5.251361] dump_stack+0x70/0x9c
[    5.251368] rwlock_bug+0x5c/0x70
[    5.251374] do_raw_write_unlock+0xbc/0xd0
[    5.251381] _raw_write_unlock+0x2c/0x60
[    5.251390] apply_kernelsu_rules+0xe4/0x140
[    5.251398] search_binary_handler+0x30/0x150
[    5.251403] exec_binprm+0x54/0x190
[    5.251409] __do_execve_file+0x53c/0x650
[    5.251415] __arm64_sys_execve+0x6c/0xa0
[    5.251421] el0_svc_common+0xb0/0x120
[    5.251426] do_el0_svc+0x18/0x20
[    5.251432] el0_sync_handler+0x148/0x190
[    5.251437] el0_sync+0x140/0x180

We are already dealing with a hack, but we now introduce another hack to prevent
this: use set_cpus_allowed_ptr() immediately before acquiring the write lock. Of
course, this can sleep as well. And for that to be ignored, leverage
raw_smp_processor_id(). We don't need to make lockdep go blind anymore.

This guarantees that even if the task sleeps during memory allocation, the
scheduler can't migrate it to another CPU. Pretty nasty way, but way better than
backporting entire SELinux from linux-5.10 just to fix a KernelSU bug that
occurs only once during boot.

from: https://github.com/Atom-X-Devs/scarlet_xiaomi_sm7325/commit/dd1d0784067e360d343d5f473ef9a98fac06ab0a

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
[vbajs]
* Adopt to kernel/Kbuild
* Add const to function defination to fix the following error:
../drivers/kernelsu/selinux/rules.c:84:63: error: returning 'const cpumask_t *' (aka 'const struct cpumask *') from a function with result type 'cpumask_t *' (aka 'struct cpumask *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
1 error generated.
Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>